FROM node:22-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
COPY prisma ./prisma
RUN npm install -g pnpm@10.6.2
RUN pnpm i prisma@^6.5.0 @prisma/client@^6.5.0

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY prisma ./prisma
# 运行 version 触发下载一下 prisma 的依赖 bin
RUN npx prisma version

ENV NODE_ENV=production
