FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY prisma ./prisma
RUN npm install --no-save --no-package-lock prisma@6.14.0 @prisma/client@6.14.0

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY prisma ./prisma

ENV NODE_ENV=production

CMD ["./node_modules/.bin/prisma", "migrate", "deploy"]
