export const BYTES_PER_MB = 1024 * 1024;

export const MAX_SERVER_ACTION_UPLOAD_MB = 50;
export const MAX_SERVER_ACTION_UPLOAD_BODY_SIZE_LIMIT = `${MAX_SERVER_ACTION_UPLOAD_MB}mb`;

export const TARGET_COMPRESSED_IMAGE_MB = 5;
export const MAX_TOTAL_NEW_REFERENCE_UPLOAD_MB = 49;

export const MAX_CLIENT_IMAGE_UPLOAD_BYTES = MAX_SERVER_ACTION_UPLOAD_MB * BYTES_PER_MB;
export const TARGET_COMPRESSED_IMAGE_BYTES = TARGET_COMPRESSED_IMAGE_MB * BYTES_PER_MB;
export const MAX_TOTAL_NEW_REFERENCE_UPLOAD_BYTES =
  MAX_TOTAL_NEW_REFERENCE_UPLOAD_MB * BYTES_PER_MB;
