ALTER TABLE "public"."AssetLogoImage"
ADD COLUMN "ossBucket" VARCHAR(255) NOT NULL,
ADD COLUMN "ossEndpoint" TEXT NOT NULL,
ADD COLUMN "ossRegion" VARCHAR(64) NOT NULL;

ALTER TABLE "public"."AssetIpImage"
ADD COLUMN "ossBucket" VARCHAR(255) NOT NULL,
ADD COLUMN "ossEndpoint" TEXT NOT NULL,
ADD COLUMN "ossRegion" VARCHAR(64) NOT NULL;

ALTER TABLE "public"."AssetProductImage"
ADD COLUMN "ossBucket" VARCHAR(255) NOT NULL,
ADD COLUMN "ossEndpoint" TEXT NOT NULL,
ADD COLUMN "ossRegion" VARCHAR(64) NOT NULL;

ALTER TABLE "public"."AssetPersonImage"
ADD COLUMN "ossBucket" VARCHAR(255) NOT NULL,
ADD COLUMN "ossEndpoint" TEXT NOT NULL,
ADD COLUMN "ossRegion" VARCHAR(64) NOT NULL;
